//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAWebService
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ArrayOfString", Namespace = "http://tempuri.org/", ItemName = "string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "PAWebService.ValidateLoginSoap")]
    public interface ValidateLoginSoap
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/HelloWorld", ReplyAction = "*")]
        System.Threading.Tasks.Task<PAWebService.HelloWorldResponse> HelloWorldAsync(PAWebService.HelloWorldRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ValidateLoginLDAP", ReplyAction = "*")]
        System.Threading.Tasks.Task<PAWebService.ValidateLoginLDAPResponse> ValidateLoginLDAPAsync(PAWebService.ValidateLoginLDAPRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ValidateLoginLDAP_v2", ReplyAction = "*")]
        System.Threading.Tasks.Task<PAWebService.ValidateLoginLDAP_v2Response> ValidateLoginLDAP_v2Async(PAWebService.ValidateLoginLDAP_v2Request request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/NOAH_AccountTransactionNextNumber", ReplyAction = "*")]
        System.Threading.Tasks.Task<PAWebService.NOAH_AccountTransactionNextNumberResponse> NOAH_AccountTransactionNextNumberAsync(PAWebService.NOAH_AccountTransactionNextNumberRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/NOAH_UpdateUnitInventoryStatus", ReplyAction = "*")]
        System.Threading.Tasks.Task<PAWebService.NOAH_UpdateUnitInventoryStatusResponse> NOAH_UpdateUnitInventoryStatusAsync(PAWebService.NOAH_UpdateUnitInventoryStatusRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/BOQ_GetNOAHMRSDocumentNumberUAT", ReplyAction = "*")]
        System.Threading.Tasks.Task<PAWebService.BOQ_GetNOAHMRSDocumentNumberUATResponse> BOQ_GetNOAHMRSDocumentNumberUATAsync(PAWebService.BOQ_GetNOAHMRSDocumentNumberUATRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/BOQ_SyncToLiveUAT", ReplyAction = "*")]
        System.Threading.Tasks.Task BOQ_SyncToLiveUATAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/BOQ_SelectTrialUAT", ReplyAction = "*")]
        System.Threading.Tasks.Task<PAWebService.BOQ_SelectTrialUATResponse> BOQ_SelectTrialUATAsync(PAWebService.BOQ_SelectTrialUATRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/BOQ_GetNOAHMRSDocumentNumber", ReplyAction = "*")]
        System.Threading.Tasks.Task<PAWebService.BOQ_GetNOAHMRSDocumentNumberResponse> BOQ_GetNOAHMRSDocumentNumberAsync(PAWebService.BOQ_GetNOAHMRSDocumentNumberRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/BOQ_SyncToLive", ReplyAction = "*")]
        System.Threading.Tasks.Task BOQ_SyncToLiveAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/BOQ_SelectTrial", ReplyAction = "*")]
        System.Threading.Tasks.Task<PAWebService.BOQ_SelectTrialResponse> BOQ_SelectTrialAsync(PAWebService.BOQ_SelectTrialRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEmployeeDetails", ReplyAction = "*")]
        System.Threading.Tasks.Task<PAWebService.GetEmployeeDetailsResponse> GetEmployeeDetailsAsync(PAWebService.GetEmployeeDetailsRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class HelloWorldRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "HelloWorld", Namespace = "http://tempuri.org/", Order = 0)]
        public PAWebService.HelloWorldRequestBody Body;

        public HelloWorldRequest()
        {
        }

        public HelloWorldRequest(PAWebService.HelloWorldRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody
    {

        public HelloWorldRequestBody()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class HelloWorldResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "HelloWorldResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public PAWebService.HelloWorldResponseBody Body;

        public HelloWorldResponse()
        {
        }

        public HelloWorldResponse(PAWebService.HelloWorldResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class HelloWorldResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string HelloWorldResult;

        public HelloWorldResponseBody()
        {
        }

        public HelloWorldResponseBody(string HelloWorldResult)
        {
            this.HelloWorldResult = HelloWorldResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ValidateLoginLDAPRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ValidateLoginLDAP", Namespace = "http://tempuri.org/", Order = 0)]
        public PAWebService.ValidateLoginLDAPRequestBody Body;

        public ValidateLoginLDAPRequest()
        {
        }

        public ValidateLoginLDAPRequest(PAWebService.ValidateLoginLDAPRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class ValidateLoginLDAPRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string ssUserName;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string ssPassword;

        public ValidateLoginLDAPRequestBody()
        {
        }

        public ValidateLoginLDAPRequestBody(string ssUserName, string ssPassword)
        {
            this.ssUserName = ssUserName;
            this.ssPassword = ssPassword;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ValidateLoginLDAPResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ValidateLoginLDAPResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public PAWebService.ValidateLoginLDAPResponseBody Body;

        public ValidateLoginLDAPResponse()
        {
        }

        public ValidateLoginLDAPResponse(PAWebService.ValidateLoginLDAPResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class ValidateLoginLDAPResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public bool ValidateLoginLDAPResult;

        public ValidateLoginLDAPResponseBody()
        {
        }

        public ValidateLoginLDAPResponseBody(bool ValidateLoginLDAPResult)
        {
            this.ValidateLoginLDAPResult = ValidateLoginLDAPResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ValidateLoginLDAP_v2Request
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ValidateLoginLDAP_v2", Namespace = "http://tempuri.org/", Order = 0)]
        public PAWebService.ValidateLoginLDAP_v2RequestBody Body;

        public ValidateLoginLDAP_v2Request()
        {
        }

        public ValidateLoginLDAP_v2Request(PAWebService.ValidateLoginLDAP_v2RequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class ValidateLoginLDAP_v2RequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string ssUserName;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string ssPassword;

        public ValidateLoginLDAP_v2RequestBody()
        {
        }

        public ValidateLoginLDAP_v2RequestBody(string ssUserName, string ssPassword)
        {
            this.ssUserName = ssUserName;
            this.ssPassword = ssPassword;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ValidateLoginLDAP_v2Response
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ValidateLoginLDAP_v2Response", Namespace = "http://tempuri.org/", Order = 0)]
        public PAWebService.ValidateLoginLDAP_v2ResponseBody Body;

        public ValidateLoginLDAP_v2Response()
        {
        }

        public ValidateLoginLDAP_v2Response(PAWebService.ValidateLoginLDAP_v2ResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class ValidateLoginLDAP_v2ResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public bool ValidateLoginLDAP_v2Result;

        public ValidateLoginLDAP_v2ResponseBody()
        {
        }

        public ValidateLoginLDAP_v2ResponseBody(bool ValidateLoginLDAP_v2Result)
        {
            this.ValidateLoginLDAP_v2Result = ValidateLoginLDAP_v2Result;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class NOAH_AccountTransactionNextNumberRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "NOAH_AccountTransactionNextNumber", Namespace = "http://tempuri.org/", Order = 0)]
        public PAWebService.NOAH_AccountTransactionNextNumberRequestBody Body;

        public NOAH_AccountTransactionNextNumberRequest()
        {
        }

        public NOAH_AccountTransactionNextNumberRequest(PAWebService.NOAH_AccountTransactionNextNumberRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class NOAH_AccountTransactionNextNumberRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string System;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string TransType;

        public NOAH_AccountTransactionNextNumberRequestBody()
        {
        }

        public NOAH_AccountTransactionNextNumberRequestBody(string System, string TransType)
        {
            this.System = System;
            this.TransType = TransType;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class NOAH_AccountTransactionNextNumberResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "NOAH_AccountTransactionNextNumberResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public PAWebService.NOAH_AccountTransactionNextNumberResponseBody Body;

        public NOAH_AccountTransactionNextNumberResponse()
        {
        }

        public NOAH_AccountTransactionNextNumberResponse(PAWebService.NOAH_AccountTransactionNextNumberResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class NOAH_AccountTransactionNextNumberResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public long NOAH_AccountTransactionNextNumberResult;

        public NOAH_AccountTransactionNextNumberResponseBody()
        {
        }

        public NOAH_AccountTransactionNextNumberResponseBody(long NOAH_AccountTransactionNextNumberResult)
        {
            this.NOAH_AccountTransactionNextNumberResult = NOAH_AccountTransactionNextNumberResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class NOAH_UpdateUnitInventoryStatusRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "NOAH_UpdateUnitInventoryStatus", Namespace = "http://tempuri.org/", Order = 0)]
        public PAWebService.NOAH_UpdateUnitInventoryStatusRequestBody Body;

        public NOAH_UpdateUnitInventoryStatusRequest()
        {
        }

        public NOAH_UpdateUnitInventoryStatusRequest(PAWebService.NOAH_UpdateUnitInventoryStatusRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class NOAH_UpdateUnitInventoryStatusRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string System;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string UnitCode;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string StatusCode;

        public NOAH_UpdateUnitInventoryStatusRequestBody()
        {
        }

        public NOAH_UpdateUnitInventoryStatusRequestBody(string System, string UnitCode, string StatusCode)
        {
            this.System = System;
            this.UnitCode = UnitCode;
            this.StatusCode = StatusCode;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class NOAH_UpdateUnitInventoryStatusResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "NOAH_UpdateUnitInventoryStatusResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public PAWebService.NOAH_UpdateUnitInventoryStatusResponseBody Body;

        public NOAH_UpdateUnitInventoryStatusResponse()
        {
        }

        public NOAH_UpdateUnitInventoryStatusResponse(PAWebService.NOAH_UpdateUnitInventoryStatusResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class NOAH_UpdateUnitInventoryStatusResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public bool NOAH_UpdateUnitInventoryStatusResult;

        public NOAH_UpdateUnitInventoryStatusResponseBody()
        {
        }

        public NOAH_UpdateUnitInventoryStatusResponseBody(bool NOAH_UpdateUnitInventoryStatusResult)
        {
            this.NOAH_UpdateUnitInventoryStatusResult = NOAH_UpdateUnitInventoryStatusResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class BOQ_GetNOAHMRSDocumentNumberUATRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "BOQ_GetNOAHMRSDocumentNumberUAT", Namespace = "http://tempuri.org/", Order = 0)]
        public PAWebService.BOQ_GetNOAHMRSDocumentNumberUATRequestBody Body;

        public BOQ_GetNOAHMRSDocumentNumberUATRequest()
        {
        }

        public BOQ_GetNOAHMRSDocumentNumberUATRequest(PAWebService.BOQ_GetNOAHMRSDocumentNumberUATRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class BOQ_GetNOAHMRSDocumentNumberUATRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public long MRSId;

        public BOQ_GetNOAHMRSDocumentNumberUATRequestBody()
        {
        }

        public BOQ_GetNOAHMRSDocumentNumberUATRequestBody(long MRSId)
        {
            this.MRSId = MRSId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class BOQ_GetNOAHMRSDocumentNumberUATResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "BOQ_GetNOAHMRSDocumentNumberUATResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public PAWebService.BOQ_GetNOAHMRSDocumentNumberUATResponseBody Body;

        public BOQ_GetNOAHMRSDocumentNumberUATResponse()
        {
        }

        public BOQ_GetNOAHMRSDocumentNumberUATResponse(PAWebService.BOQ_GetNOAHMRSDocumentNumberUATResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class BOQ_GetNOAHMRSDocumentNumberUATResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string BOQ_GetNOAHMRSDocumentNumberUATResult;

        public BOQ_GetNOAHMRSDocumentNumberUATResponseBody()
        {
        }

        public BOQ_GetNOAHMRSDocumentNumberUATResponseBody(string BOQ_GetNOAHMRSDocumentNumberUATResult)
        {
            this.BOQ_GetNOAHMRSDocumentNumberUATResult = BOQ_GetNOAHMRSDocumentNumberUATResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class BOQ_SelectTrialUATRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "BOQ_SelectTrialUAT", Namespace = "http://tempuri.org/", Order = 0)]
        public PAWebService.BOQ_SelectTrialUATRequestBody Body;

        public BOQ_SelectTrialUATRequest()
        {
        }

        public BOQ_SelectTrialUATRequest(PAWebService.BOQ_SelectTrialUATRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class BOQ_SelectTrialUATRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public long MRSid;

        public BOQ_SelectTrialUATRequestBody()
        {
        }

        public BOQ_SelectTrialUATRequestBody(long MRSid)
        {
            this.MRSid = MRSid;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class BOQ_SelectTrialUATResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "BOQ_SelectTrialUATResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public PAWebService.BOQ_SelectTrialUATResponseBody Body;

        public BOQ_SelectTrialUATResponse()
        {
        }

        public BOQ_SelectTrialUATResponse(PAWebService.BOQ_SelectTrialUATResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class BOQ_SelectTrialUATResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string BOQ_SelectTrialUATResult;

        public BOQ_SelectTrialUATResponseBody()
        {
        }

        public BOQ_SelectTrialUATResponseBody(string BOQ_SelectTrialUATResult)
        {
            this.BOQ_SelectTrialUATResult = BOQ_SelectTrialUATResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class BOQ_GetNOAHMRSDocumentNumberRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "BOQ_GetNOAHMRSDocumentNumber", Namespace = "http://tempuri.org/", Order = 0)]
        public PAWebService.BOQ_GetNOAHMRSDocumentNumberRequestBody Body;

        public BOQ_GetNOAHMRSDocumentNumberRequest()
        {
        }

        public BOQ_GetNOAHMRSDocumentNumberRequest(PAWebService.BOQ_GetNOAHMRSDocumentNumberRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class BOQ_GetNOAHMRSDocumentNumberRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public long MRSId;

        public BOQ_GetNOAHMRSDocumentNumberRequestBody()
        {
        }

        public BOQ_GetNOAHMRSDocumentNumberRequestBody(long MRSId)
        {
            this.MRSId = MRSId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class BOQ_GetNOAHMRSDocumentNumberResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "BOQ_GetNOAHMRSDocumentNumberResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public PAWebService.BOQ_GetNOAHMRSDocumentNumberResponseBody Body;

        public BOQ_GetNOAHMRSDocumentNumberResponse()
        {
        }

        public BOQ_GetNOAHMRSDocumentNumberResponse(PAWebService.BOQ_GetNOAHMRSDocumentNumberResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class BOQ_GetNOAHMRSDocumentNumberResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string BOQ_GetNOAHMRSDocumentNumberResult;

        public BOQ_GetNOAHMRSDocumentNumberResponseBody()
        {
        }

        public BOQ_GetNOAHMRSDocumentNumberResponseBody(string BOQ_GetNOAHMRSDocumentNumberResult)
        {
            this.BOQ_GetNOAHMRSDocumentNumberResult = BOQ_GetNOAHMRSDocumentNumberResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class BOQ_SelectTrialRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "BOQ_SelectTrial", Namespace = "http://tempuri.org/", Order = 0)]
        public PAWebService.BOQ_SelectTrialRequestBody Body;

        public BOQ_SelectTrialRequest()
        {
        }

        public BOQ_SelectTrialRequest(PAWebService.BOQ_SelectTrialRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class BOQ_SelectTrialRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public long MRSid;

        public BOQ_SelectTrialRequestBody()
        {
        }

        public BOQ_SelectTrialRequestBody(long MRSid)
        {
            this.MRSid = MRSid;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class BOQ_SelectTrialResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "BOQ_SelectTrialResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public PAWebService.BOQ_SelectTrialResponseBody Body;

        public BOQ_SelectTrialResponse()
        {
        }

        public BOQ_SelectTrialResponse(PAWebService.BOQ_SelectTrialResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class BOQ_SelectTrialResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string BOQ_SelectTrialResult;

        public BOQ_SelectTrialResponseBody()
        {
        }

        public BOQ_SelectTrialResponseBody(string BOQ_SelectTrialResult)
        {
            this.BOQ_SelectTrialResult = BOQ_SelectTrialResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetEmployeeDetailsRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetEmployeeDetails", Namespace = "http://tempuri.org/", Order = 0)]
        public PAWebService.GetEmployeeDetailsRequestBody Body;

        public GetEmployeeDetailsRequest()
        {
        }

        public GetEmployeeDetailsRequest(PAWebService.GetEmployeeDetailsRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class GetEmployeeDetailsRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string inUsername;

        public GetEmployeeDetailsRequestBody()
        {
        }

        public GetEmployeeDetailsRequestBody(string inUsername)
        {
            this.inUsername = inUsername;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetEmployeeDetailsResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetEmployeeDetailsResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public PAWebService.GetEmployeeDetailsResponseBody Body;

        public GetEmployeeDetailsResponse()
        {
        }

        public GetEmployeeDetailsResponse(PAWebService.GetEmployeeDetailsResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class GetEmployeeDetailsResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public PAWebService.ArrayOfString GetEmployeeDetailsResult;

        public GetEmployeeDetailsResponseBody()
        {
        }

        public GetEmployeeDetailsResponseBody(PAWebService.ArrayOfString GetEmployeeDetailsResult)
        {
            this.GetEmployeeDetailsResult = GetEmployeeDetailsResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ValidateLoginSoapChannel : PAWebService.ValidateLoginSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class ValidateLoginSoapClient : System.ServiceModel.ClientBase<PAWebService.ValidateLoginSoap>, PAWebService.ValidateLoginSoap
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public ValidateLoginSoapClient(EndpointConfiguration endpointConfiguration) :
                base(ValidateLoginSoapClient.GetBindingForEndpoint(endpointConfiguration), ValidateLoginSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ValidateLoginSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(ValidateLoginSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ValidateLoginSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(ValidateLoginSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ValidateLoginSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PAWebService.HelloWorldResponse> PAWebService.ValidateLoginSoap.HelloWorldAsync(PAWebService.HelloWorldRequest request)
        {
            return base.Channel.HelloWorldAsync(request);
        }

        public System.Threading.Tasks.Task<PAWebService.HelloWorldResponse> HelloWorldAsync()
        {
            PAWebService.HelloWorldRequest inValue = new PAWebService.HelloWorldRequest();
            inValue.Body = new PAWebService.HelloWorldRequestBody();
            return ((PAWebService.ValidateLoginSoap)(this)).HelloWorldAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PAWebService.ValidateLoginLDAPResponse> PAWebService.ValidateLoginSoap.ValidateLoginLDAPAsync(PAWebService.ValidateLoginLDAPRequest request)
        {
            return base.Channel.ValidateLoginLDAPAsync(request);
        }

        public System.Threading.Tasks.Task<PAWebService.ValidateLoginLDAPResponse> ValidateLoginLDAPAsync(string ssUserName, string ssPassword)
        {
            PAWebService.ValidateLoginLDAPRequest inValue = new PAWebService.ValidateLoginLDAPRequest();
            inValue.Body = new PAWebService.ValidateLoginLDAPRequestBody();
            inValue.Body.ssUserName = ssUserName;
            inValue.Body.ssPassword = ssPassword;
            return ((PAWebService.ValidateLoginSoap)(this)).ValidateLoginLDAPAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PAWebService.ValidateLoginLDAP_v2Response> PAWebService.ValidateLoginSoap.ValidateLoginLDAP_v2Async(PAWebService.ValidateLoginLDAP_v2Request request)
        {
            return base.Channel.ValidateLoginLDAP_v2Async(request);
        }

        public System.Threading.Tasks.Task<PAWebService.ValidateLoginLDAP_v2Response> ValidateLoginLDAP_v2Async(string ssUserName, string ssPassword)
        {
            PAWebService.ValidateLoginLDAP_v2Request inValue = new PAWebService.ValidateLoginLDAP_v2Request();
            inValue.Body = new PAWebService.ValidateLoginLDAP_v2RequestBody();
            inValue.Body.ssUserName = ssUserName;
            inValue.Body.ssPassword = ssPassword;
            return ((PAWebService.ValidateLoginSoap)(this)).ValidateLoginLDAP_v2Async(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PAWebService.NOAH_AccountTransactionNextNumberResponse> PAWebService.ValidateLoginSoap.NOAH_AccountTransactionNextNumberAsync(PAWebService.NOAH_AccountTransactionNextNumberRequest request)
        {
            return base.Channel.NOAH_AccountTransactionNextNumberAsync(request);
        }

        public System.Threading.Tasks.Task<PAWebService.NOAH_AccountTransactionNextNumberResponse> NOAH_AccountTransactionNextNumberAsync(string System, string TransType)
        {
            PAWebService.NOAH_AccountTransactionNextNumberRequest inValue = new PAWebService.NOAH_AccountTransactionNextNumberRequest();
            inValue.Body = new PAWebService.NOAH_AccountTransactionNextNumberRequestBody();
            inValue.Body.System = System;
            inValue.Body.TransType = TransType;
            return ((PAWebService.ValidateLoginSoap)(this)).NOAH_AccountTransactionNextNumberAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PAWebService.NOAH_UpdateUnitInventoryStatusResponse> PAWebService.ValidateLoginSoap.NOAH_UpdateUnitInventoryStatusAsync(PAWebService.NOAH_UpdateUnitInventoryStatusRequest request)
        {
            return base.Channel.NOAH_UpdateUnitInventoryStatusAsync(request);
        }

        public System.Threading.Tasks.Task<PAWebService.NOAH_UpdateUnitInventoryStatusResponse> NOAH_UpdateUnitInventoryStatusAsync(string System, string UnitCode, string StatusCode)
        {
            PAWebService.NOAH_UpdateUnitInventoryStatusRequest inValue = new PAWebService.NOAH_UpdateUnitInventoryStatusRequest();
            inValue.Body = new PAWebService.NOAH_UpdateUnitInventoryStatusRequestBody();
            inValue.Body.System = System;
            inValue.Body.UnitCode = UnitCode;
            inValue.Body.StatusCode = StatusCode;
            return ((PAWebService.ValidateLoginSoap)(this)).NOAH_UpdateUnitInventoryStatusAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PAWebService.BOQ_GetNOAHMRSDocumentNumberUATResponse> PAWebService.ValidateLoginSoap.BOQ_GetNOAHMRSDocumentNumberUATAsync(PAWebService.BOQ_GetNOAHMRSDocumentNumberUATRequest request)
        {
            return base.Channel.BOQ_GetNOAHMRSDocumentNumberUATAsync(request);
        }

        public System.Threading.Tasks.Task<PAWebService.BOQ_GetNOAHMRSDocumentNumberUATResponse> BOQ_GetNOAHMRSDocumentNumberUATAsync(long MRSId)
        {
            PAWebService.BOQ_GetNOAHMRSDocumentNumberUATRequest inValue = new PAWebService.BOQ_GetNOAHMRSDocumentNumberUATRequest();
            inValue.Body = new PAWebService.BOQ_GetNOAHMRSDocumentNumberUATRequestBody();
            inValue.Body.MRSId = MRSId;
            return ((PAWebService.ValidateLoginSoap)(this)).BOQ_GetNOAHMRSDocumentNumberUATAsync(inValue);
        }

        public System.Threading.Tasks.Task BOQ_SyncToLiveUATAsync()
        {
            return base.Channel.BOQ_SyncToLiveUATAsync();
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PAWebService.BOQ_SelectTrialUATResponse> PAWebService.ValidateLoginSoap.BOQ_SelectTrialUATAsync(PAWebService.BOQ_SelectTrialUATRequest request)
        {
            return base.Channel.BOQ_SelectTrialUATAsync(request);
        }

        public System.Threading.Tasks.Task<PAWebService.BOQ_SelectTrialUATResponse> BOQ_SelectTrialUATAsync(long MRSid)
        {
            PAWebService.BOQ_SelectTrialUATRequest inValue = new PAWebService.BOQ_SelectTrialUATRequest();
            inValue.Body = new PAWebService.BOQ_SelectTrialUATRequestBody();
            inValue.Body.MRSid = MRSid;
            return ((PAWebService.ValidateLoginSoap)(this)).BOQ_SelectTrialUATAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PAWebService.BOQ_GetNOAHMRSDocumentNumberResponse> PAWebService.ValidateLoginSoap.BOQ_GetNOAHMRSDocumentNumberAsync(PAWebService.BOQ_GetNOAHMRSDocumentNumberRequest request)
        {
            return base.Channel.BOQ_GetNOAHMRSDocumentNumberAsync(request);
        }

        public System.Threading.Tasks.Task<PAWebService.BOQ_GetNOAHMRSDocumentNumberResponse> BOQ_GetNOAHMRSDocumentNumberAsync(long MRSId)
        {
            PAWebService.BOQ_GetNOAHMRSDocumentNumberRequest inValue = new PAWebService.BOQ_GetNOAHMRSDocumentNumberRequest();
            inValue.Body = new PAWebService.BOQ_GetNOAHMRSDocumentNumberRequestBody();
            inValue.Body.MRSId = MRSId;
            return ((PAWebService.ValidateLoginSoap)(this)).BOQ_GetNOAHMRSDocumentNumberAsync(inValue);
        }

        public System.Threading.Tasks.Task BOQ_SyncToLiveAsync()
        {
            return base.Channel.BOQ_SyncToLiveAsync();
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PAWebService.BOQ_SelectTrialResponse> PAWebService.ValidateLoginSoap.BOQ_SelectTrialAsync(PAWebService.BOQ_SelectTrialRequest request)
        {
            return base.Channel.BOQ_SelectTrialAsync(request);
        }

        public System.Threading.Tasks.Task<PAWebService.BOQ_SelectTrialResponse> BOQ_SelectTrialAsync(long MRSid)
        {
            PAWebService.BOQ_SelectTrialRequest inValue = new PAWebService.BOQ_SelectTrialRequest();
            inValue.Body = new PAWebService.BOQ_SelectTrialRequestBody();
            inValue.Body.MRSid = MRSid;
            return ((PAWebService.ValidateLoginSoap)(this)).BOQ_SelectTrialAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PAWebService.GetEmployeeDetailsResponse> PAWebService.ValidateLoginSoap.GetEmployeeDetailsAsync(PAWebService.GetEmployeeDetailsRequest request)
        {
            return base.Channel.GetEmployeeDetailsAsync(request);
        }

        public System.Threading.Tasks.Task<PAWebService.GetEmployeeDetailsResponse> GetEmployeeDetailsAsync(string inUsername)
        {
            PAWebService.GetEmployeeDetailsRequest inValue = new PAWebService.GetEmployeeDetailsRequest();
            inValue.Body = new PAWebService.GetEmployeeDetailsRequestBody();
            inValue.Body.inUsername = inUsername;
            return ((PAWebService.ValidateLoginSoap)(this)).GetEmployeeDetailsAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ValidateLoginSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ValidateLoginSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ValidateLoginSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.11.244:8020/ValidateLogin.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ValidateLoginSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.11.244:8020/ValidateLogin.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        public enum EndpointConfiguration
        {

            ValidateLoginSoap,

            ValidateLoginSoap12,
        }
    }
}
